os: linux
language: php
php: 8.0
install: composer install
script:
  - composer require athletic/athletic:~0.1 --dev
  - cat composer.json
  - php test.php

jobs:
  include:
    - dist: bionic
    - dist: focal
