#
os: linux
language: php
php: 8.0
install: composer install
script:
  - COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-lowest --no-interaction --prefer-install=auto --quiet
  - composer global require seld/jsonlint
  - curl https://repo.packagist.org/p2/athletic/athletic.json | ~/.composer/vendor/bin/jsonlint

jobs:
  include:
    - dist: bionic
    - dist: focal
