#
os: linux
language: php
php: 8.0
install:
  - sudo apt update && sudo apt --only-upgrade install curl -y
  - composer install
script:
  - COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-lowest --no-interaction --prefer-install=auto --quiet
  - composer global require seld/jsonlint
  - sudo phpdismod curl
  - curl https://repo.packagist.org/p2/athletic/athletic.json | /home/travis/.config/composer/vendor/bin/jsonlint
  - curl https://repo.packagist.org/p2/spryker/payone.json | /home/travis/.config/composer/vendor/bin/jsonlint
  - curl https://repo.packagist.org/p2/spryker/payone.json
  - wget https://repo.packagist.org/p2/athletic/athletic.json
  - wget https://repo.packagist.org/p2/spryker/payone.json
  - /home/travis/.config/composer/vendor/bin/jsonlint athletic.json
  - /home/travis/.config/composer/vendor/bin/jsonlint payone.json

jobs:
  include:
    - dist: bionic
    - dist: focal
